version: '2'
services:
    opennlp:
        build: opennlp
    brat:
        build: brat
        ports:
            - 80:8001
        volumes:
            - brat-cfg:/opt/brat/configurations
            - brat-data:/opt/brat/data
        depends_on:
            - "opennlp"
volumes:
    brat-cfg:
    brat-data:
